"""mcp servers and per-project mcp switches

Revision ID: 0809b33a1694
Revises: b6ecfa854d64
Create Date: 2026-10-06 01:22:48.431155

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0809b33a1694"
down_revision: str | Sequence[str] | None = "b6ecfa854d64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Additions only, so the release still serving keeps working: a table it never reads, and a column with a
    constant default, which Postgres adds without rewriting chats."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_servers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=1024), server_default="", nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("auth", sa.String(length=16), nullable=False),
        sa.Column("header_name", sa.String(length=128), nullable=True),
        sa.Column("secret", sa.Text(), nullable=True),
        sa.Column("tools", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("icon", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_mcp_servers_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mcp_servers")),
        sa.UniqueConstraint("user_id", "name", name=op.f("uq_mcp_servers_user_id")),
    )
    op.add_column(
        "chats",
        sa.Column("disabled_mcp_servers", postgresql.ARRAY(sa.String(length=64)), server_default="{}", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "disabled_mcp_servers")
    op.drop_table("mcp_servers")
    # ### end Alembic commands ###
