"""run worker lease

Revision ID: 0a9ff048c441
Revises: 41096dce84bd
Create Date: 2026-10-01 15:12:56.900968

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a9ff048c441"
down_revision: str | Sequence[str] | None = "41096dce84bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("runs", sa.Column("claimed_by", sa.String(length=255), nullable=True))
    op.add_column("runs", sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("runs", sa.Column("cancel_requested", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("runs", sa.Column("message_id", sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("runs", "message_id")
    op.drop_column("runs", "cancel_requested")
    op.drop_column("runs", "lease_expires_at")
    op.drop_column("runs", "claimed_by")
    # ### end Alembic commands ###
