"""baseline schema

Revision ID: 937a780e272e
Revises:
Create Date: 2026-09-23 14:31:18.121313

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "937a780e272e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the schema, or adopt one that already exists."""
    # This repository created its schema with `create_all` before Alembic existed,
    # so a deployed database already has every table below. Detect that and record
    # the revision instead of re-creating it: the alternative is a manual
    # `alembic stamp head` on each existing database, with a window where a deploy
    # fails halfway. A fresh database has no `users` table and is built normally.
    if sa.inspect(op.get_bind()).has_table("users"):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sandbox_runtimes",
        sa.Column("chat_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("sandbox_id", sa.String(length=255), nullable=True),
        sa.Column("template_id", sa.String(length=255), nullable=False),
        sa.Column("generation", sa.String(length=64), nullable=False),
        sa.Column("revision_id", sa.String(length=36), nullable=True),
        sa.Column("reusable", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("spend_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("chat_id", name=op.f("pk_sandbox_runtimes")),
        sa.UniqueConstraint("operation_id", name=op.f("uq_sandbox_runtimes_operation_id")),
        sa.UniqueConstraint("sandbox_id", name=op.f("uq_sandbox_runtimes_sandbox_id")),
    )
    op.create_index(op.f("ix_sandbox_runtimes_state"), "sandbox_runtimes", ["state"], unique=False)
    op.create_table(
        "storage_deletions",
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("object_key", name=op.f("pk_storage_deletions")),
    )
    op.create_table(
        "storage_usage",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("uploaded", sa.Integer(), nullable=False),
        sa.Column("downloaded", sa.Integer(), nullable=False),
        sa.Column("uploaded_ops", sa.Integer(), server_default="0", nullable=False),
        sa.Column("downloaded_ops", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("day", name=op.f("pk_storage_usage")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("bio", sa.String(length=280), server_default="", nullable=False),
        sa.Column("email_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_query_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("plan", sa.String(length=32), server_default="free", nullable=False),
        sa.Column("tokens_remaining", sa.Integer(), nullable=False),
        sa.Column("tokens_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "auth_identities",
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_identities_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("provider", "subject", name=op.f("pk_auth_identities")),
        sa.UniqueConstraint("user_id", "provider", name=op.f("uq_auth_identities_user_id")),
    )
    op.create_index(op.f("ix_auth_identities_user_id"), "auth_identities", ["user_id"], unique=False)
    op.create_table(
        "auth_tokens",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=24), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("request_ip", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_auth_tokens_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("digest", name=op.f("pk_auth_tokens")),
    )
    op.create_index(op.f("ix_auth_tokens_purpose"), "auth_tokens", ["purpose"], unique=False)
    op.create_index(op.f("ix_auth_tokens_user_id"), "auth_tokens", ["user_id"], unique=False)
    op.create_table(
        "chats",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("app_url", sa.String(length=1024), nullable=True),
        sa.Column("latest_saved_revision_id", sa.String(length=36), nullable=True),
        sa.Column("latest_verified_revision_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_chats_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chats")),
    )
    op.create_table(
        "spend_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("reserved_nanos", sa.BigInteger(), nullable=False),
        sa.Column("amount_nanos", sa.BigInteger(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "amount_nanos >= 0 AND reserved_nanos >= 0", name=op.f("ck_spend_entries_amounts_nonnegative")
        ),
        sa.CheckConstraint("ends_at >= starts_at", name=op.f("ck_spend_entries_window_ordered")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_spend_entries_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spend_entries")),
    )
    op.create_index(op.f("ix_spend_entries_user_id"), "spend_entries", ["user_id"], unique=False)
    op.create_index("ix_spend_user_window", "spend_entries", ["user_id", "ends_at", "starts_at"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chat_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=True),
        sa.Column("tool_calls", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], name=op.f("fk_messages_chat_id_chats"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chat_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("events", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("workflow", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("log_key", sa.String(length=512), nullable=True),
        sa.Column("log_sha256", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], name=op.f("fk_runs_chat_id_chats"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(op.f("ix_runs_chat_id"), "runs", ["chat_id"], unique=False)
    op.create_index(op.f("ix_runs_status"), "runs", ["status"], unique=False)
    op.create_table(
        "transcript_entries",
        sa.Column("chat_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], name=op.f("fk_transcript_entries_chat_id_chats"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("chat_id", "sequence", name=op.f("pk_transcript_entries")),
    )
    op.create_table(
        "project_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chat_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("archive_sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("template_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"], ["chats.id"], name=op.f("fk_project_revisions_chat_id_chats"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_project_revisions_run_id_runs"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_revisions")),
        sa.UniqueConstraint("object_key", name=op.f("uq_project_revisions_object_key")),
    )
    op.create_index(op.f("ix_project_revisions_chat_id"), "project_revisions", ["chat_id"], unique=False)
    op.create_index(op.f("ix_project_revisions_run_id"), "project_revisions", ["run_id"], unique=False)
    op.create_index(op.f("ix_project_revisions_status"), "project_revisions", ["status"], unique=False)
    op.create_table(
        "run_events",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "sequence", name=op.f("pk_run_events")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_events")
    op.drop_index(op.f("ix_project_revisions_status"), table_name="project_revisions")
    op.drop_index(op.f("ix_project_revisions_run_id"), table_name="project_revisions")
    op.drop_index(op.f("ix_project_revisions_chat_id"), table_name="project_revisions")
    op.drop_table("project_revisions")
    op.drop_table("transcript_entries")
    op.drop_index(op.f("ix_runs_status"), table_name="runs")
    op.drop_index(op.f("ix_runs_chat_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_table("messages")
    op.drop_index("ix_spend_user_window", table_name="spend_entries")
    op.drop_index(op.f("ix_spend_entries_user_id"), table_name="spend_entries")
    op.drop_table("spend_entries")
    op.drop_table("chats")
    op.drop_index(op.f("ix_auth_tokens_user_id"), table_name="auth_tokens")
    op.drop_index(op.f("ix_auth_tokens_purpose"), table_name="auth_tokens")
    op.drop_table("auth_tokens")
    op.drop_index(op.f("ix_auth_identities_user_id"), table_name="auth_identities")
    op.drop_table("auth_identities")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("storage_usage")
    op.drop_table("storage_deletions")
    op.drop_index(op.f("ix_sandbox_runtimes_state"), table_name="sandbox_runtimes")
    op.drop_table("sandbox_runtimes")
    # ### end Alembic commands ###
